# Butterfly 主题图片配置建议
# 将以下配置添加到你的 _config.butterfly.yml 中

# 导航栏 logo
nav:
  logo: /images/branding/logo.png

# 基础图片设置
favicon: /images/branding/favicon.png

avatar:
  img: /images/branding/avatar.jpg
  effect: true  # 头像悬停效果

# 页面横幅设置
default_top_img: /images/banners/default-banner.jpg
index_img: /images/banners/index-banner.jpg
archive_img: /images/banners/archive-banner.jpg
tag_img: /images/banners/tag-banner.jpg
category_img: /images/banners/category-banner.jpg

# 网站背景
background: /images/backgrounds/site-bg.jpg

# 页脚背景
footer_img: /images/backgrounds/footer-bg.jpg

# 文章封面设置
cover:
  index_enable: true
  aside_enable: true
  archives_enable: true
  default_cover:
    - /images/covers/default-1.jpg
    - /images/covers/default-2.jpg
    - /images/covers/default-3.jpg
    - /images/covers/default-4.jpg
    - /images/covers/default-5.jpg

# 错误页面图片
error_img:
  flink: /images/errors/broken-link.gif
  post_page: /images/errors/404-post.jpg

error_404:
  enable: true
  subtitle: 'Page Not Found'
  background: /images/errors/404-bg.jpg

# 特定标签/分类的横幅图片
tag_per_img:
  - AI: /images/banners/ai-banner.jpg
  - 技术: /images/banners/tech-banner.jpg

category_per_img:
  - 人工智能: /images/banners/ai-category.jpg
  - 编程技术: /images/banners/programming.jpg
